# Generated by Django 4.1.7 on 2023-08-11 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AveragePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.TextField()),
                ('individual_average_prices', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('overall_average_price', models.FloatField()),
            ],
            options={
                'db_table': 'average_prices',
            },
        ),
        migrations.CreateModel(
            name='FkHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('low_img', models.TextField(default='')),
                ('high_img', models.TextField(default='')),
                ('type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('floor_area', models.CharField(max_length=255)),
                ('plot_area', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('costs', models.TextField(default='')),
                ('vr_img', models.TextField(default='')),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'fk_houses',
            },
        ),
       
        migrations.CreateModel(
            name='LyyskiHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('low_img', models.TextField(default='')),
                ('high_img', models.TextField(default='')),
                ('type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('floor_area', models.CharField(max_length=255)),
                ('plot_area', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('costs', models.TextField(default='')),
                ('vr_img', models.TextField(default='')),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'lyyski_houses',
            },
        ),
        migrations.CreateModel(
            name='MaklerHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('low_img', models.TextField(default='')),
                ('high_img', models.TextField(default='')),
                ('type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('floor_area', models.CharField(max_length=255)),
                ('plot_area', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('costs', models.TextField(default='')),
                ('vr_img', models.TextField(default='')),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'maklar_houses',
            },
        ),
    ]
