# Generated by Django 4.0.4 on 2023-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_fkhouse_price_alter_formhouse_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('municipality', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'map_data',
            },
        ),
    ]
