# Generated by Django 4.0.4 on 2023-08-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_mapdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapdata',
            options={'managed': False},
        ),
    ]
