# Generated by Django 4.0.4 on 2023-09-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_mapdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktiaHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('low_img', models.TextField(default='')),
                ('high_img', models.TextField(default='')),
                ('type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('floor_area', models.CharField(max_length=255)),
                ('plot_area', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('costs', models.TextField(default='')),
                ('vr_img', models.TextField(default='')),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'aktia_houses',
            },
        ),
    ]
