# Generated by Django 4.1.7 on 2023-07-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaklerHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('low_img', models.TextField()),
                ('high_img', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('floor_area', models.CharField(max_length=255)),
                ('plot_area', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'maklar_houses',
            },
        ),
    ]
